# Generated by Django 5.2.5 on 2025-08-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0018_alter_hiveconfiguration_xai_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiveconfiguration',
            name='stt_backend',
            field=models.CharField(choices=[('local', 'Local (faster-whisper)'), ('openai', 'OpenAI Whisper')], default='openai', max_length=16),
        ),
        migrations.AddField(
            model_name='hiveconfiguration',
            name='stt_lang',
            field=models.CharField(default='en', max_length=16),
        ),
        migrations.AddField(
            model_name='hiveconfiguration',
            name='stt_url',
            field=models.CharField(blank=True, help_text='Local STT endpoint, e.g. http://127.0.0.1:8001/stt', max_length=255, null=True),
        ),
    ]
