# Generated by Django 5.2.5 on 2025-08-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0019_hiveconfiguration_stt_backend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiveconfiguration',
            name='stt_compute',
            field=models.CharField(choices=[('int8', 'int8 (CPU best)'), ('int8_float16', 'int8/FP16 (mixed)'), ('float16', 'float16 (GPU best)'), ('float32', 'float32')], default='int8', max_length=16),
        ),
        migrations.AddField(
            model_name='hiveconfiguration',
            name='stt_device',
            field=models.CharField(choices=[('auto', 'Auto'), ('cpu', 'CPU'), ('cuda', 'CUDA (GPU)')], default='auto', max_length=8),
        ),
    ]
