# Generated by Django 5.2.5 on 2025-08-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0020_hiveconfiguration_stt_compute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiveconfiguration',
            name='stt_model',
            field=models.CharField(blank=True, help_text='Selected local STT model path (inside container)', max_length=255, null=True),
        ),
    ]
